name: Must run on custom runner

#on: push

on:
 workflow_dispatch:

jobs:
  init:
    runs-on: self-hosted
    steps:
      - run: echo 'hello cloud gurus'
      - run: echo $HOSTNAME
      - run: pwd
      - run: bash /runners/mostrar.sh
      - run: cd /runners && bash ./mostrar.sh
      - run: pwd
