name: Must run on custom runner

#on: push

on:
  workflow_dispatch:
    inputs:
      nombres:
        description: 'Nombres '
        type: choice
        options:
        - Marcelo
        - Rodri
 

jobs:
  init:
    runs-on: self-hosted
    steps:
      - run: echo 'hello cloud gurus'
      - run: echo $HOSTNAME
      - run : echo "${{ github.event.inputs.nombres }}"
      - run : echo "${{ github.event.inputs.nombres }}" > /tmp/nombres.txt
      - run: pwd
      - run: bash /runners/mostrar.sh
      - run: cd /runners && bash ./mostrar.sh
      - run: pwd
