name: Terramform apply

on:
 workflow_dispatch:

jobs:
  init:
    runs-on: self-hosted
    steps:
      - name: Terraform init
        run: cd /home/devops/custom-runner/kind-terra && sudo terraform init
      - name: Terraform plan
        run: cd /home/devops/custom-runner/kind-terra && sudo terraform plan
      - name: Terraform apply
        run: cd /home/devops/custom-runner/kind-terra && sudo terraform apply --auto-approve
  
